### ISSUE TITLE
Not working with HA 2022.7.0

### ISSUE THREAD

**Issue by udicol** [Miicroo/ha-birthdays#7]
The integration not work with new version: 2022.7.0.

**Comment by dharvey242** [comment]
Same here

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/birthdays/__init__.py:46
Integration: birthdays (documentation)
First occurred: 06:38:31 (1 occurrences)
Last logged: 06:38:31

Error during setup of component birthdays
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/birthdays/__init__.py", line 46, in async_setup
    await asyncio.wait(tasks, loop=hass.loop)
TypeError: wait() got an unexpected keyword argument 'loop'

**Comment by dharvey242** [comment]
I changed:
`await asyncio.wait(tasks, loop=hass.loop)`

to read
`await asyncio.wait(tasks)`

In line 46 /config/custom_components/birthdays/init.py

And seems to be working after a restart

**Comment by udicol** [comment]
Fixed !
Thank !

**Comment by Miicroo** [comment]
@udicol @dharvey242 Wow, you guys are quick! Thanks for the fix, pushed it to master now! 😄

**Comment by Miicroo** [comment]
Verified, closing
